# mcfx_convolver configuration
# ------------------------
/cd 
#
#
#
#/impulse/read   <input> <output> <gain> <delay> <offset> <length> <channel> <file>
/impulse/read 1 1 1.0 0 0 0 1 IKOFilter_SH_In1.wav
/impulse/read 2 2 1.0 0 0 0 2 IKOFilter_SH_In1.wav
/impulse/read 3 3 1.0 0 0 0 3 IKOFilter_SH_In1.wav
/impulse/read 4 4 1.0 0 0 0 4 IKOFilter_SH_In1.wav
/impulse/read 5 5 1.0 0 0 0 5 IKOFilter_SH_In1.wav
/impulse/read 6 6 1.0 0 0 0 6 IKOFilter_SH_In1.wav
/impulse/read 7 7 1.0 0 0 0 7 IKOFilter_SH_In1.wav
/impulse/read 8 8 1.0 0 0 0 8 IKOFilter_SH_In1.wav
/impulse/read 9 9 1.0 0 0 0 9 IKOFilter_SH_In1.wav
/impulse/read 10 10 1.0 0 0 0 10 IKOFilter_SH_In1.wav
/impulse/read 11 11 1.0 0 0 0 11 IKOFilter_SH_In1.wav
/impulse/read 12 12 1.0 0 0 0 12 IKOFilter_SH_In1.wav
/impulse/read 13 13 1.0 0 0 0 13 IKOFilter_SH_In1.wav
/impulse/read 14 14 1.0 0 0 0 14 IKOFilter_SH_In1.wav
/impulse/read 15 15 1.0 0 0 0 15 IKOFilter_SH_In1.wav
/impulse/read 16 16 1.0 0 0 0 16 IKOFilter_SH_In1.wav
/impulse/read 17 17 1.0 0 0 0 17 IKOFilter_SH_In1.wav
/impulse/read 18 18 1.0 0 0 0 18 IKOFilter_SH_In1.wav
/impulse/read 19 19 1.0 0 0 0 19 IKOFilter_SH_In1.wav
/impulse/read 20 20 1.0 0 0 0 20 IKOFilter_SH_In1.wav
